
on:
  pull_request:
    branches:
      - main

jobs:
  quick-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quick Scan
        run: |
         
            echo "repository_url: ${{ github.event.repository.html_url }}"
            echo "branch_name: ${{ github.event.pull_request.head.ref }}"
            echo "issue_number: ${{ github.event.number }}"
            
