on:
  pull_request:
    branches:
      - main

jobs:
  quick-scan:
    runs-on: ubuntu-latest
    env:
      AUDIT_AGENT_TOKEN: ${{ secrets.AUDIT_AGENT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Quick Scan
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Api-Key: $AUDIT_AGENT_TOKEN" \
            -d '{
              "repositoryURL": "${{ github.event.repository.html_url }}",
              "branchName": "${{ github.event.pull_request.head.ref }}",
              "issueNumber": ${{ github.event.number }},
              "commitHash": "${{ github.event.pull_request.head.sha }}",
              "contractFiles": ["contracts/Will.sol"]
            }' \
            https://322e-2409-40f2-103a-a4a5-b583-aa3e-db82-b03c.ngrok-free.app/api/v1/scanner/quick-scan/launch
